---
- name: Backup Cisco IOS Configurations
  hosts: cisco_devices  # 在inventory中定义的思科设备组
  gather_facts: false
  
  vars:
    backup_path: "./backups/{{inventory_hostname}}"  # 备份文件保存路径
    timestamp: "{{lookup('pipe','date +%Y%m%d_%H%M%S')}}"  # 获取当前时间戳
  
  tasks:
    - name: Create backup directory if it does not exist
      file:
        path: "{{backup_path}}"
        state: directory
      delegate_to: localhost
      run_once: true

    - name: Backup running configuration
      ios_command:
        commands: show running-config
      register: config
      retries: 3
      delay: 10
      until: config is not failed

    - name: Save configuration to file
      copy:
        content: "{{config.stdout[0]}}"
        dest: "{{backup_path}}/{{inventory_hostname}}_{{timestamp}}.conf"
      delegate_to: localhost

    - name: Display backup status
      debug:
        msg: "Configuration backup completed for {{inventory_hostname}}"
